### ISSUE TITLE
Home non connectée / users * / revoir les logos

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#1]
Supprimer le trait sur le logo non connecté header :

![Chaleur-Rugby](https://user-images.githubusercontent.com/17780287/143553642-aa6a36d3-c60c-4d29-95d4-c16af5cb78d4.png)

Enlever le logo 3 diamants sur le footer :
![Chaleur-Rugby (1)](https://user-images.githubusercontent.com/17780287/143554386-440d2e0f-4733-4dc7-8486-9118fbefb807.png)

**Comment by CharlieSaso** [comment]
Ok corrigé

**Comment by Sinoe** [comment]
Ok, en fait fail il faut laisser 1 logo Mitsu mais qui n'est pas le même.
En attente visuel de Julien

**Comment by CharlieSaso** [comment]
Ok par contre c'était l'enfer avec ce logo il est beaucoup trop large.
Du coup vu que je suis un peu un ouf je me suis permis de tenter un truc sur le logo..
Dis moi ce que t'en penses, en tout cas en PJ ce à quoi ça ressemblerais si on laisse leur logo en l'état

![Chaleur-Rugby - Google Chrome](https://user-images.githubusercontent.com/21694987/143993486-71a05159-19a2-4273-b937-ebe5e299515c.jpg)

**Comment by Sinoe** [comment]
Je vois pas le changement tu as push quelque chose ?

**Comment by Sinoe** [comment]
ok bon je crois qu'on était obligé de mettre le logo sur une ligne, je vais voir avec le client...

**Comment by Sinoe** [comment]
On est donc bien obligé de conserver le logo sur une ligne.
Thomas à refait la créa pour ça (à changer dans le header et le footer) => pas la peine pour le contenu de la home 

Le .XD est à jour
![Groupe 18072](https://user-images.githubusercontent.com/17780287/144264733-aeceb0c7-9174-4fa9-adff-dfe40532450d.png)
![Groupe 18071](https://user-images.githubusercontent.com/17780287/144264738-b1fc6649-e1b8-4f3d-96ab-70ce70ec9dd5.png)


![Chaleur-Rugby (7)](https://user-images.githubusercontent.com/17780287/144264672-2718943d-83af-4081-9e55-5f808f6d7b61.png)

Logo au format SVG ici : 
[logo_ligne.svg.gz](https://github.com/FK-Agency/ME-chaleur-rugby/files/7635208/logo_ligne.svg.gz)

**Comment by CharlieSaso** [comment]
OK

**Comment by Sinoe** [comment]
PAr contre que pour la home non connectée please...
