### ISSUE TITLE
Général // Header / ajouter un box-shadow au scroll

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#14]
Ajouter un box shadow au scroll sur le header, là quand on est sur fond blanc ça fait bizarre

![Chaleur-Rugby (6)](https://user-images.githubusercontent.com/17780287/143613380-38a3c5b9-cf96-471e-abd6-3da098cb948e.png)

**Comment by CharlieSaso** [comment]
Ok corrigé
