### ISSUE TITLE
Page LP // Users * / l'icone de la LP n'est pas dynamique

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#15]
Sur la page https://chaleur-rugby.fk-agency.net/landing-quizz/ ce n'est pas l'icône ajoutée dans le B.O. qui est affichée, mais l'icône concours photo par défaut

![Modifier-la-page-‹-Chaleur-Rugby-—-WordPress](https://user-images.githubusercontent.com/17780287/143616193-06d206f0-1a36-414f-9829-d54cbbd14533.png)
![Landing-Concours-quizz-–-Chaleur-Rugby (1)](https://user-images.githubusercontent.com/17780287/143616202-56901ce9-b069-487c-9096-8c651bd74b21.png)

**Comment by CharlieSaso** [comment]
Ok corrigé

**Comment by Sinoe** [comment]
ok visuel à changer => voir avec Thomas
