### ISSUE TITLE
Général / Users connectés / menu jeu

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#16]
Doublon au niveau des jeux dans le menu :

![Screenshot 2021-11-29 at 09-55-32 Quizz – 01 – Chaleur-Rugby](https://user-images.githubusercontent.com/17780287/143837493-050d1204-d0ef-4960-a339-e2565fd5cf12.png)

Alors qu'il n'y a qu'1 page :
![Pages-‹-Chaleur-Rugby-—-WordPress](https://user-images.githubusercontent.com/17780287/143837373-b7ac0230-38fc-4018-b3f1-c0cc178b83b2.png)

**Comment by CharlieSaso** [comment]
Corrigé

**Comment by Sinoe** [comment]
ok merci
