### ISSUE TITLE
Pages comptes // modifier l'image de fond + ajouter un lien dans le header

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#17]
- [ ] Changer l'image de fond => revoir avec Thomas pour ne pas avoir de Kanji en morceaux....
- [ ] Ajouter un lien vers la page de profil sur le nom de l'utilisateur dans le header

**Comment by Sinoe** [comment]
Voilà l'image 
![password – 1](https://user-images.githubusercontent.com/17780287/144013549-5b2ec574-f498-4a14-92b7-2590689cb343.png)
:

**Comment by CharlieSaso** [comment]
Ok c'est fait
