### ISSUE TITLE
Page inscription // profil distributeur / autocomplete

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#18]
Sur la page d'inscription au profil distrib, afficher les options de l'autocomplete à partir de la saisie de 2 caractères (pour ne pas rendre trop facilement accessible l'ensemble de la liste).

Peut-être en utilisant la fonctionnalité select2 AJAX et en lançant les requêtes après 2 char ?

**Comment by CharlieSaso** [comment]
C'est en place.
ça m'a pris 2h j'ai du construire une page pour faire la requête en php.. nan je rigole :) check la P
![PrtScr capture_4](https://user-images.githubusercontent.com/21694987/143995721-881e83af-59f3-4208-826f-291a9a49bc0c.jpg)
J

**Comment by Sinoe** [comment]
magnifique !
