### ISSUE TITLE
Page de Connexion // users* / rediriger les utilisateurs sur la home connecté suite à une connexion

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#19]
Suite à la connexion d'un user le rediriger vers la home, pour le moment, ils restent sur la page de connexion avec le message : 

Vous êtes connecté·e en tant que sinoe.grattepanche@gmail.com
Cliquez pour vous déconnecter

**Comment by CharlieSaso** [comment]
ok c'est redirigé sur la home
