### ISSUE TITLE
Home non connectée / Users* / calage image bloc home > contenu home > contenu

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#2]
Revoir le calage de l'image bloc home > contenu home > contenu

![Chaleur-Rugby (2)](https://user-images.githubusercontent.com/17780287/143556544-b4dd82d5-fe75-4414-be2a-9701124a6a67.png)

**Comment by CharlieSaso** [comment]
Ok corrigé

**Comment by Sinoe** [comment]
ok
