### ISSUE TITLE
B.O. // transformer le champs Box texte en WYSIWYG

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#20]
Transformer le champs Box - texte de l'en-tête des pages modèles LP en WYSIWYG pour permettre d'être plus libre niveau mise en page (demande client)

![Modifier-la-page-‹-Chaleur-Rugby-—-WordPress (1)](https://user-images.githubusercontent.com/17780287/143863088-7a9aa655-313f-4311-8165-48d1e6a859b0.png)

**Comment by CharlieSaso** [comment]
Ok par contre il va falloir faire des ajustements en css.
De base on est sur un text-align center, ça va péter les ul
Je met tout à gauche et dans le wysiwyg si on veut recentrer le texte on le formate dans l'éditeur ?

**Comment by CharlieSaso** [comment]
Du coup j'ai passé en ferré à gauche de base

**Comment by Sinoe** [comment]
ok pour moi, je rouvre le ticket si le client à des remarques, mais ça ira je pense
