### ISSUE TITLE
TO DO DEV

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#21]
- [x] Remontée Insta Mitsubishi (me prévenir quand ça sera ok pour que je lui fasse valider l'app de récupération des images) Le compte Insta est https://www.instagram.com/mitsubishielectric_fr/?hl=fr
- [x] Envoie de mail via SMTP Mitsu (SendinBlue )
- [x] Créer un compte G.A. et l'ajouter sur le site (ajouter en admin sinoe.grattepanche@fk-agency.com et Julien.BARRE@fra.mee.com)
- [x] Ajouter Tarte au citron
- [x] revoir le contenu et styler la page 404 
- [ ] Contrat de maintenance à prévoir
- [x] Installer WP Secure
- [ ] Si possible ajouter tracking Hubspot (vérifier la limitation des domaines)

**Comment by CharlieSaso** [comment]
Corriger renouvellement de mot de passe

**Comment by CharlieSaso** [comment]
Remonter Instagram

**Comment by Sinoe** [comment]
Compte Insta : https://www.instagram.com/mitsubishielectric_fr/?hl=fr

**Comment by CharlieSaso** [comment]
Order by date pour les CP matchs

**Comment by Sinoe** [comment]
Visuel de la 404 :
[Image 64.svg.gz](https://github.com/FK-Agency/ME-chaleur-rugby/files/7635564/Image.64.svg.gz)
