### ISSUE TITLE
B.O. // Landing page jeu / structure

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#22]
Demande client, sur la LP jeu, il faudrait stp :
1. descendre le bloc CTA secondaire en-dessous du texte principal,
2. Ajouter un autre bloc de texte sous ce champs déplacé.

Si pas trop long, possible de les mettre en mode repeater ? où ils peuvent choisir, un bloc texte ou un bloc CTA et d'en mettre autant qu'ils veulent ?

**Comment by CharlieSaso** [comment]
OK j'ai ajouté le repéteur.
J'ai laissé le bouton de la box ou il était, si on le veut pas il suffit de pas le remplir


![Landing Concours photo Exemplaire – Chaleur-Rugby - Google Chrome](https://user-images.githubusercontent.com/21694987/144178731-e36df26b-0c18-45f1-a079-324a9688a4e1.jpg)
![Modifier la page ‹ Chaleur-Rugby — WordPress - Google Chrome_2](https://user-images.githubusercontent.com/21694987/144178735-440060fe-1c28-454d-a78f-9999275b07a7.jpg)

**Comment by Sinoe** [comment]
Mince désolé il manquait mon screen au ticket, c'était tout le bloc rouge que j'appelais "bloc CTA" sorry

![Landing-Concours-photo-–-Chaleur-Rugby](https://user-images.githubusercontent.com/17780287/144200248-46ed0ed8-6e0f-46dd-b089-983b0f581c5b.png)

**Comment by CharlieSaso** [comment]
OK
