### ISSUE TITLE
Page jeux concours ajouter un param : ?user={email compte user} dans l'URL

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#23]
Peux-tu stp ajouter un param : ?user={email compte user} dans l'URL
Exemples : https://fk-agency.net/test-drimify/?user=sinoe.grattepanche@fk-agency.com // https://chaleur-rugby.fk-agency.net/jeux/concours-photo/?user=sinoe.grattepanche@gmail.com

C'est le seul moyen que j'ai trouvé pour récupérer l'adresse email de l'user dans Drimify

Voilà ce que je fais, si tu as une autre solution qui permet de le passer sans qu'il soit dans l'URL n'hésites pas ;)
```js
$(window).on('load', function(){
    if($('input#email').length){
        //On est sur la bonne page Fill input avec les infos récupérés par getTopLinkInfo()
        if(result){
            //On récupère la source de l'iframe la plus haute qui contient l'URL FK en param
            console.log(result['parentsHrefs']['0']);
            const urlParams = new URLSearchParams(result['parentsHrefs']['0']);
            const myParam = urlParams.get('sharingurl');
            //On récupère le param qui nous intéresse ('sharingurl')
            console.log(myParam);
            if(myParam){
                const sourceURL = new URL(myParam);
                const originParams = new URLSearchParams(sourceURL.search);
                //On récupère le param qui nous intéresse de la page FK ('user')
                const email = originParams.get('user');
                console.log(email);
                if(email){
                    // si on a une valeur on prérempli le champs
                    console.log('fill email');
                    $('input#email').val(email);
                }
            }
        }
    }
 });

 function getTopLinkInfo() {
 var topLinkInfo = {};
 try {
 topLinkInfo.topHref = top.location.href;
 }
 catch (error) {
 try {
 var ancestorOrigins = window.location.ancestorOrigins;
 if (ancestorOrigins) {
 topLinkInfo.parentsDomains = [];
 for (var i = 0; i < ancestorOrigins.length; i++) {
 topLinkInfo.parentsDomains.unshift(ancestorOrigins[i]);
 }
 }
 var bottomW = window;
 var topW = window.parent;
 topLinkInfo.parentsReferrers = [];
 topLinkInfo.parentsHrefs = [];
 while (topW !== bottomW) {
 topLinkInfo.parentsReferrers.unshift(bottomW.document.referrer);
 topLinkInfo.parentsHrefs.unshift(bottomW.location.href);
 bottomW = bottomW.parent;
 topW = topW.parent;
 }
 } catch (error) {}
 }
 return topLinkInfo;
 }
 var result = getTopLinkInfo();
```

**Comment by CharlieSaso** [comment]
Très sincèrement juste après lecture de ton code j'ai compris que c'était une galère donc j'ai pas cherché plus loin.
A la rigueur on peut peut-être hasher l'email dans l'url mais étant donné que je me dit qu'on est sur un espace privé, est-ce vraiment à faire ?

La seul condition importante c'est d'associer le jeux a la catégorie photo concours car c'est ça qui va rajouter le paramètre ?user=*email*

**Comment by Sinoe** [comment]
oui je te confirme c'est galère... j'ai pas réussi à récupérer le contenu de la page FK, chaque fois des problèmes CORS ou autres... et c'est ce que je me dis aussi pour la partie privée, + à part les geeks, je pense que personne ne regarde ce qu'il se passe dans l'URL... 
Donc idéalement si t'arrives à le mettre que pout les jeux concours photo c'est cool, sinon j'ai envie de dire, on garde le principe pour toutes les pages jeux, comme ça ça peut être ajouté sur tous les liens de manière plus pérenne peut-être...

**Comment by CharlieSaso** [comment]
Soit je laisse comme la c'est, donc faut sélectionner la catégorie concours photo pour avoir le parameter user, soit je le met pour chaque page et on en parle plus comme ça t'as même pas à te prendre la tête à sélectionner la catégorie. Surtout que si t'oublis ça marchera pas.

**Comment by Sinoe** [comment]
ok bon laissons comme ça pour le moment merci
