### ISSUE TITLE
Home + pages LP concours // revoir les fonds pour supprimer les kanji morcelé

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#25]
1. Sur la home 
Enlevé le morceau de kanji sur la vidéo 
![Chaleur-Rugby (8)](https://user-images.githubusercontent.com/17780287/144266252-859dfef6-a683-43b9-8664-00e5afb294c6.png)
2. Sur les pages LP concours :
Changer le fond header avec celui-là 
![bg-photo-lg](https://user-images.githubusercontent.com/17780287/144267670-347c54c5-e9f7-42c1-9bec-802292026d74.jpg)
Et masquer l'image https://chaleur-rugby.fk-agency.net/wp-content/themes/chaleur-rugby/assets/build/img/deco2.png qui ne doit pas apparaître

**Comment by CharlieSaso** [comment]
OK
