### ISSUE TITLE
Home page // connecté - non connecté / revoir la mise en page

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#26]
Revoir la mise en page de la home :
1. mettre un border-radius sur l'image de la signature,
2. supprimer le combo logo dans la partie texte de gauche,
3. Remonter le logo sur la partie blanche centré sur toute la largeur en gardant de l'espace entre les blocs texte-image et le bloc bleu "plateforme de marque"
![Chaleur-Rugby (9)](https://user-images.githubusercontent.com/17780287/144269168-e6f2c976-43bc-4e67-becd-fbacac8da904.png)

**Comment by CharlieSaso** [comment]
OOK
