### ISSUE TITLE
Pages inscription / profil / ... // Select / ordre des options

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#27]
Sur les select (fonction, interlocuteurs ME, etc...) des pages profils, création de compte, inscription, modification du compte etc...
Peut-on :
1. mettre les options "Autre" en dernier toujours (là on dirait que c'est pas ordre alphabétique, à la limite pas besoin),
2. masquer le champs n/a
???

![Page-de-profil-–-Chaleur-Rugby (3)](https://user-images.githubusercontent.com/17780287/144270163-0e79b677-6592-4b47-a16e-044d3578c706.png)

**Comment by CharlieSaso** [comment]
OK

**Comment by Sinoe** [comment]
GG
