### ISSUE TITLE
Header // User connecté pas de jeux / masqué le menu déroulant jeu

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#30]
Masquer le menu déroulant "Jeux" pour les users qui n'ont pas de jeux en cours

![Chaleur-Rugby (10)](https://user-images.githubusercontent.com/17780287/144385544-4e5f4e80-f9b6-4f47-8d60-c50665671915.png)

**Comment by CharlieSaso** [comment]
OK
