### ISSUE TITLE
Flux création de compte

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#41]
Sur le mail lors de la création de compte, le lien de connexion n'est pas bon (inscription VS connexion) :
![Vos-informations-de-connexion-Chaleur-Rugby-sinoe-grattepanche-fk-agency-com-Messagerie-FK-Agency](https://user-images.githubusercontent.com/17780287/144592935-b42df328-a1cb-4ba3-8f2d-4652b8d24cac.png)

A la première connexion, on a encore du texte en anglais, où ça ce change ?
![Screenshot 2021-12-03 at 12-08-47 Page de profil – Chaleur-Rugby](https://user-images.githubusercontent.com/17780287/144593185-7eaa5e32-88da-4674-a25c-0e3c8fbe628a.png)

**Comment by CharlieSaso** [comment]
Lien mail, ok c'est le mauvais shortcode qui était appelé ( au cas ou liste des shortcode : https://rocketgeek.com/plugins/wp-members/docs/customizing-emails/email-shortcodes/ )
![PrtScr capture_16](https://user-images.githubusercontent.com/21694987/144755463-e898e86f-b648-406d-b004-da753438c849.jpg)
![WP-Members ‹ Chaleur-Rugby — WordPress - Google Chrome](https://user-images.githubusercontent.com/21694987/144755486-be0b8f82-867f-4ae4-833e-4d69388da7e1.jpg)

Dans l'extension de wp-member ( Editor ) qui est censé te permettre de traduire les champs il manque pas mal de champs finalement.
Du coup pour combler les trous j'ai installer WPML et je traduis les trucs qui trainent comme ça : 

![Comptes ‹ Chaleur-Rugby — WordPress - Google Chrome](https://user-images.githubusercontent.com/21694987/144755826-d0e60a3e-4f69-47ee-ae7a-e0235de938e0.jpg)

![Localisation du thème et des plugins ‹ Chaleur-Rugby — WordPress - Google Chrome](https://user-images.githubusercontent.com/21694987/144755828-d229a716-0f57-4b0b-b605-e40158d7c5b5.jpg)
![Traduction de chaînes ‹ Chaleur-Rugby — WordPress - Google Chrome](https://user-images.githubusercontent.com/21694987/144755830-9db6c4ba-a31c-4180-8758-f33ea8e5d20b.jpg)

j'ai mis ça : 
![Traduction de chaînes ‹ Chaleur-Rugby — WordPress - Google Chrome_2](https://user-images.githubusercontent.com/21694987/144755856-256be2d1-9a97-4d14-8a31-9d71be0c2289.jpg)

**Comment by Sinoe** [comment]
ok on peut personnalisé les templates pour les mails avec du html ?

**Comment by CharlieSaso** [comment]
Yep on l'a déjà fait sur un autre client d'ailleurs
