### ISSUE TITLE
Date des matchs en Anglais

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#42]
Les dates des matchs sont en anglais, je n'avais pas remarqué avant mais je crois que c'était bien en FR...

![Chaleur-Rugby (14)](https://user-images.githubusercontent.com/17780287/144600961-957b4b31-e472-478e-9cad-0e8584c7620c.png)

Bref j'ai fait ça :
Ajout `setlocale` en `fr_FR.UTF-8` et enlever le `utf8_encode` sur `c-calendar__date`
```php
setlocale(LC_TIME, 'fr_FR.UTF-8');
?>


		<div class="c-calendar">

			<ol class="c-calendar__list">

				<?php foreach ($matchs as $item):
					$date_de_la_rencontre = get_field('date_de_la_rencontre',$item->ID);
					$player_1 = get_field('player_1',$item->ID);
					$player_2 = get_field('player_2',$item->ID);
					$ville = get_field('ville',$item->ID);
					$event = get_field('event',$item->ID);
				?>

				<li class="c-calendar__item">
					<div class="c-calendar__date"><?php  echo strftime("%d %B", strtotime($date_de_la_rencontre));?></div>


```

Regarde si ça te semble ok et récupère le code stp

**Comment by CharlieSaso** [comment]
C'est good j'avais mis le mauvais setlocale(LC_TIME, 'fr_FR') VS setlocale(LC_TIME, 'fr_FR.UTF-8');
cimer en tout cas, et du coup c'est bien classé grâce au champ acf date des match
