### ISSUE TITLE
Lien sur le label de la page d'inscirption

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#44]
Peux-tu stp ajouter un lien sur le label de la page d'inscription :
En cliquant sur cette case, j’accepte les <a href="https://chaleur-rugby.fk-agency.net/wp-content/uploads/2021/12/20211202_CGU_Chaleur_Rugby.pdf" target="_blank">Conditions Générales d’Utilisation</a> de la Plateforme.

Attention la valeur du fichier PDF sera à mettre à jour une fois le site en prod...

**Comment by CharlieSaso** [comment]
Crappy time !
![Options ‹ Chaleur-Rugby — WordPress - Google Chrome](https://user-images.githubusercontent.com/21694987/144756804-6b724ada-473c-4d56-b44e-575a5ffb2876.jpg)
