### ISSUE TITLE
Liste interlocuteur Mitsubishi => 2 fois le choix ne sais pas

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#49]
Sur la page : https://www.chaleur-rugby.com/page-dinscription/ il y a 2 fois `Ne sais pas` dans la liste des interlocuteurs MEE, je pense que tu l'as ajouté dans le code directement et moi en code

**Comment by CharlieSaso** [comment]
ok mais toi tu l'as ajouté comment ?

**Comment by Sinoe** [comment]
Ben je l'ai mis là : https://www.chaleur-rugby.com/wp-admin/edit.php?s=ne+sais&post_status=all&post_type=interlocuteur-mee&action=-1&m=0&lang=fr&paged=1&action2=-1

**Comment by CharlieSaso** [comment]
Ha ba c'est censé bien ce passé normalement dans ce cas la.. je regarde

**Comment by Sinoe** [comment]
ok merci
