### ISSUE TITLE
Liste business partner's à pré-enregistrer

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#51]
Voilà la liste des BP à pré-registred sur la plateforme please

[Liste Business Partners - Pré-enregistrement.xlsx](https://github.com/FK-Agency/ME-chaleur-rugby/files/7676749/Liste.Business.Partners.-.Pre-enregistrement.xlsx)

**Comment by CharlieSaso** [comment]
c'est importé, exemple ici : https://www.chaleur-rugby.com/page-dinscription/?mail=anne@benoit-guyot.fr

**Comment by Sinoe** [comment]
merci !
