### ISSUE TITLE
Select page inscription / édition de profil  - Typo

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#52]
Peux-tu stp mettre la bonne typo sur les select des pages inscription et édition de profil stp, là c'est le bon vieux Times New Roman et c'est un peu moche

**Comment by CharlieSaso** [comment]
Tu peux m'envoyer une capture pck de mon coté sur les select les typo sont bien en DIN que ce soit sur la page d'inscription ou la page de profil

**Comment by Sinoe** [comment]
Ok bon j'ai recheck du coup, ça bug sur FF chez moi, mais je vois bien le font-family hérité en css donc je sais pas trop pourquoi... chelou

Bref le screen pour la science, et je close le ticket pour l'instant...

![Capture d’écran (130)](https://user-images.githubusercontent.com/17780287/145236961-1dcfc762-3438-4ef6-93c4-62e6bd3ff67d.png)
