### ISSUE TITLE
Import home partenaires please

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#53]
Peux-tu importer ces pre-registred utilisateurs (home partenaires) stp :
[Liste Home Partenaires.xlsx](https://github.com/FK-Agency/ME-chaleur-rugby/files/7686179/Liste.Home.Partenaires.xlsx)

**Comment by CharlieSaso** [comment]
Ok c'est importé, exemple ici : https://www.chaleur-rugby.com/page-dinscription/?mail=alexandre.s.techniques@gmail.com
