### ISSUE TITLE
Header / Footer // remplacer le logo MEE pour les Home Partenaires

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#54]
Il faudrait remplacer le logo présent dans le header et le footer pour les utilisateurs logués avec le profil home partenaires en utilisant celui-là please : 

![V1 Full gras](https://user-images.githubusercontent.com/17780287/145424859-2fdbd4c3-7bd9-4f4c-ae0f-8a300e8051e3.png)

**Comment by CharlieSaso** [comment]
Ok par contre l'image est méga cheum.
J'ai mis visible quand t'es admin aussi pour que tu puisses la voir

**Comment by Sinoe** [comment]
vu que c'est très moche, on ne publie pas en prod, ils vont se démerder pour ajouter eux-mêmes le logo dans la home connecté des home partenaires, donc désolé mais peux-tu annuler cette modif stp
