### ISSUE TITLE
Page inscription // ajout d'un tooltips

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#55]
Ajout d'un tooltips à côté du champs Code Espace MyClub => `?` cerclé exemple : 
https://codepen.io/wsol/pen/BawaZgg
https://codepen.io/ddparkas/pen/GRvrgLz

Le but du Tooltips est d'indiquer comment / où récupérer son code, donc prévoir l'ajout d'une image et potentiellement de textes.

Prévoir aussi que cette demande va sûrement être répétée pour les autres profils à qui un code est demandé.

![Page-d’inscription-–-Chaleur-Rugby (2)](https://user-images.githubusercontent.com/17780287/145425598-02588846-5720-4ff8-8b86-30b77d653e56.png)

**Comment by CharlieSaso** [comment]
j'ai ajouté un champ dans Options où tu peux gérer ce qu'il y a dans la box.
![Options ‹ Chaleur-Rugby — WordPress - Google Chrome](https://user-images.githubusercontent.com/21694987/145599804-38e6a5f3-7259-4345-8bec-4dee1872928d.jpg)

pour l'inté j'ai fait au feeling hein : https://chaleur-rugby.fk-agency.net/page-dinscription/

rapport à ça : "Prévoir aussi que cette demande va sûrement être répétée pour les autres profils à qui un code est demandé." => j'ai pas compris, normalement il n'y a qu'un rôle qui doit avoir le code client en plus.

En l'état la mécanique c'est que le champ Code client a le "?" et que la box est à remplir dans le BO dans "Options", il va falloir prévoir que le contenu va être différent selon le profil ?...

**Comment by Sinoe** [comment]
ok go client pour push en prod stp
