### ISSUE TITLE
Page inscription // générer une URL par profil

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#56]
Peux-tu stp générer une URL par profil pour que le champs profil soit pré-selectionné et les champs sup affichés de base si on visite cette page

**Comment by CharlieSaso** [comment]
Ok c'est en prod

https://www.chaleur-rugby.com/page-dinscription/?type_de_profil=architecte
https://www.chaleur-rugby.com/page-dinscription/?type_de_profil=bureau-detude
https://www.chaleur-rugby.com/page-dinscription/?type_de_profil=distributeur
https://www.chaleur-rugby.com/page-dinscription/?type_de_profil=installateur
https://www.chaleur-rugby.com/page-dinscription/?type_de_profil=installateurs-business-partenaires
https://www.chaleur-rugby.com/page-dinscription/?type_de_profil=installateurs-home-partenaires
https://www.chaleur-rugby.com/page-dinscription/?type_de_profil=maitre-douvrage
https://www.chaleur-rugby.com/page-dinscription/?type_de_profil=mitsubishi-electric

**Comment by Sinoe** [comment]
Merci !
