### ISSUE TITLE
Page LP jeux // inté

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#59]
Sur la page LP jeux :

Peux-tu stp retirer la largeur max sur `c-desc__content` pour qu'il prenne la largeur de `o-wrapper` (1124px) pour pouvoir afficher des images "full width"
```html
<div class="c-desc">
	<div class="o-wrapper" style="border: 1px solid red;">
		<div class="c-desc__content" style="border: 1px solid green;">
			<div class="c-quiz__conclusion">
						</div>
		</div>
	</div>
</div>
```
![Screenshot 2022-01-10 at 11-03-59 Concours Photo Hyper Heating Ultimate – Fin – Chaleur-Rugby](https://user-images.githubusercontent.com/17780287/148748556-741af5c9-6cf3-4d85-802d-b665a9dccc28.png)

Ainsi que le Kanji à gauche pour qu'il ne gêne pas le texte qui fera peut-être + que cette taille.

Possible solution :
1. sur le template renommer la classe `c-desc__content` en `c-desc__content-max`
2. en css ajouter `.page-template-page-landing-jeux  .c-desc::before{display:none;}`

**Comment by CharlieSaso** [comment]
ok c'est good
