### ISSUE TITLE
Page de changement de password / Users * / problème inté + langue

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#6]
Revoir l'inté sur la page de changement de MDP (1ere connexion) 

![Page-de-profil-–-Chaleur-Rugby](https://user-images.githubusercontent.com/17780287/143561616-5fb8e438-3a13-4475-b7a7-b8c809c5fe65.png)

- [ ] 1. Le texte en haut à gauche n'est pas centré
- [x] 2. Le contenu est en Anglais (dont le 1er label > confirm current pass)
- [ ] 3. possible de mettre un petit border-radius sur la div password strenght required pour être conforme à la créa ?

**Comment by Sinoe** [comment]
Revoir l'inté sur les pages comptes, certains texte ne sont pas centrés

**Comment by CharlieSaso** [comment]
Ok corrigé

**Comment by CharlieSaso** [comment]
Ok corrigé
Pour la trad j'ai ajouté WPML comme ça si demain on trouve un autre truc c'est traduisible depuis le BO

**Comment by Sinoe** [comment]
ok perfect !
