### ISSUE TITLE
Page prono // recette front - Desktop

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#61]
- [x] Dans le header page prono : masquer la partie Profil si tous les champs sont vides
![Page-de-pronostics-–-Chaleur-Rugby](https://user-images.githubusercontent.com/17780287/149338426-3d20e5dc-7497-4ed1-b52b-62aabf13feb8.png)

- [x] S'il n'y a pas de matchs sur lesquels parier : ajouter la phrase `Pas de match à pronostiquer` et ajouter de la marge pour espacer le footer
![Page-de-pronostics-–-Chaleur-Rugby (1)](https://user-images.githubusercontent.com/17780287/149338740-c1bd269a-ecdc-4a8b-9fed-13786fe19da2.png)

- [x] Petit bug sur le nombre de points remportés sur la page de résultat, dans le cas ci-dessous le joueur n'a pas participé et donc pas gagné de points...
![Page-de-pronostics-–-Chaleur-Rugby (2)](https://user-images.githubusercontent.com/17780287/149338956-538f9d9d-9377-4dca-8e63-649a9a3f4e08.png)

- [x] sur la page matchs terminés : retirer l'état hover sur les boutons et le cursor pointer
![Page-de-pronostics-–-Chaleur-Rugby (3)](https://user-images.githubusercontent.com/17780287/149339322-7802e21a-c778-4b0d-9e50-153a3ee8c22e.png)

- [x] sur la page classement : centrer le contenu verticalement 
![Page-de-Classement-–-Chaleur-Rugby](https://user-images.githubusercontent.com/17780287/149339986-c6b90b28-b15b-42b9-ba5f-ac2eca94b1a4.png)

Possible fix (ajout de `align-items: center;` ):
```css
.c-classement__line {
    padding: 20px 50px;
    display: flex;
    justify-content: space-between;
    align-items: center;
}
```

**Comment by CharlieSaso** [comment]
C'est good
