### ISSUE TITLE
TO DO dev - V2 

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#63]
Voici ce qu'il reste à faire pour le lancement de lundi par ordre de priorité :
- [x] Pages classement (finalisation de la page Agence)
- [x] Intégration de la nouvelle maquette des lots
- [x] Remontée du prochain match jouable sur la home (masquer l'ensemble du bloc si pas de match)
- [x] Traiter les retours recette (#61 #62 )

Si possible d'ici lundi, sinon à faire après MEP :
- [x] Remontée de l'iframe jeu Drimify dans le contenu de la page LP directement
- [x] Ajouter un bouton dans le B.O. pour lancer le CRON manuellement (un target="_blank" sur les pages matchs suffit par exemple...)

**Comment by Sinoe** [comment]
2 petites modifs sur l'Iframe jeu stp :
1. ajouter l'adresse mail du joueur en param de l'Iframe (comme pour les concours photos),
2. Lien ancre sur le container : 
- Ajouter un ID propre sur le container de l'Iframe, 
- permettre de faire un lien ancre sur le bouton "Jouer"
![Modifier-la-page-‹-Chaleur-Rugby-—-WordPress (2)](https://user-images.githubusercontent.com/17780287/150162675-3d79a018-8314-4c27-843d-b5ad8e1a889f.png)
- Prendre en compte le header fix pour le scroll de cette ancre (si besoin)

**Comment by CharlieSaso** [comment]
Pour ajouter l'adresse il faut sélectionner le type de jeux et le mettre sur Concours photo : 
![Modifier la page ‹ Chaleur-Rugby — WordPress - Google Chrome_6](https://user-images.githubusercontent.com/21694987/150499756-906f38ad-ed92-4c06-98a5-ccc5c15a335c.jpg)

Pour activer l'ancre j'ai ajouter un true/false dans l'admin : 
![Modifier la page ‹ Chaleur-Rugby — WordPress - Google Chrome_7](https://user-images.githubusercontent.com/21694987/150499842-c3ef4eee-849b-4a0d-8128-ff8ea9a7717d.jpg)

J'ai testé ici : https://chaleur-rugby.fk-agency.net/concours-photo-rugby/
