### ISSUE TITLE
Intégration des jeux iframes - garder les jeux sur la page jeu

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#66]
Hello,

Après en avoir parler au client, on aura des jeux comme actuellement sur la page jeu, et des jeux directement en Iframe sur la LP jeu.
Peux-tu ajouter une option dans le B.O. pour choisir sur la LP si le jeu doit être en iframe ou rediriger sur la page jeu stp.

**Comment by CharlieSaso** [comment]
C'est sur la preprod j'attend le go

**Comment by Sinoe** [comment]
Ok merci, peux-tu juste ajouter l'adresse email dans l'URL de la page LP jeux aussi stp (en fait c'est le param de l'URL qui sert à pré-remplir le mail dans le jeu et pas celui sur l'Iframe...)
`?user={{email@email.com}}`
Cf comportement sur : https://chaleur-rugby.fk-agency.net/jeux/concours-photo-references/?user=charlie.sasorith@fk-agency.com

**Comment by CharlieSaso** [comment]
Ok c'est sur le même principe que la page jeux il faut sélectionner le type "concour Photos" pour que l'adresse mail apparaisse dans l'URL
![Modifier la page ‹ Chaleur-Rugby — WordPress - Google Chrome_8](https://user-images.githubusercontent.com/21694987/151958906-eb988164-cf93-46e9-8694-61a80b8f5731.jpg)
