### ISSUE TITLE
Lien prono sur user autre que Ditributeur

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#67]
Hello,

Le lien vers le jeu prono apparaît avec un role `Installateurs Business Partner`

![Chaleur-Rugby (2)](https://user-images.githubusercontent.com/17780287/151166295-ee25c4d4-8b26-4c5d-9d0d-479da31c5f8b.png)

Si tu peux corriger ça stp

**Comment by CharlieSaso** [comment]
Ok c'est poussé en prod, à check plz

**Comment by Sinoe** [comment]
C'est good merci !
