### ISSUE TITLE
Page classement ordre des matchs terminés

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#68]
Peux-tu stp inverser l'ordre sur la page prono > matchs terminés : https://www.chaleur-rugby.com/page-de-pronostics/
Pour que les matchs soient affichés par date décroissante (le plus récent terminé en premier : France Italie en haut actuellement)

**Comment by CharlieSaso** [comment]
C'est good c'est changé
![Page de pronostics – Chaleur-Rugby - Google Chrome_5](https://user-images.githubusercontent.com/21694987/152777239-c8dc80f5-dfa0-4586-a636-17e02a0bc7a8.jpg)

**Comment by Sinoe** [comment]
Merci !
