### ISSUE TITLE
Page de profil // Users * / pages non intégrées + principe sur la page d'inscription pas pris en compte

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#7]
Les pages de profil ne sont pas intégrées et la page de modification n'est pas ok (select vide + tous les champs apparaissant) :

![Page-de-profil-–-Chaleur-Rugby (2)](https://user-images.githubusercontent.com/17780287/143563347-7a2cae3f-142c-4c0f-b37e-51394ea41fda.png)
![Page-de-profil-–-Chaleur-Rugby (1)](https://user-images.githubusercontent.com/17780287/143563229-6771beed-02da-4d5e-aacd-e008ed8af6c7.png)

**Comment by CharlieSaso** [comment]
Ok corrigé, pour le moment j'ai laissé masqué les fields à voir ce qu'on laisse éditable

**Comment by Sinoe** [comment]
ok pour ça (nouveau ticket sur les pages comptes à venir)
