### ISSUE TITLE
Titre page classement société > renommer le titre de la page (individuel VS société)

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#70]
quand ont clique sur classement des sociétés il y a toujours marqué à gauche « Votre classement individuel ».
Il faudrait mettre : `Classement société`

![image001 (3)](https://user-images.githubusercontent.com/17780287/154442729-f27b3454-e4e8-446e-8100-14b2d30017c1.png)

**Comment by CharlieSaso** [comment]
ok c'est good
