### ISSUE TITLE
FIN JEU PRONO 

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#74]
A faire en prod direct stp 

- [ ] HOME modifier le texte :
![Chaleur-Rugby (2)](https://user-images.githubusercontent.com/17780287/155998940-4bb2297d-dc6c-4ae1-bcd7-2a2aca7e1257.png)
texte p : `Le jeu de Pronostic est terminé, consultez votre classement et celui de votre agence juste ici !`
texte button : `classement` (et faire un lien direct vers la page classement)

- [ ] Menu :
Modifier le lien pour arriver sur la page classement directement

- [ ] Page classement :
Retirer le bouton `Faites vos pronostics`
![Page-de-Classement-–-Chaleur-Rugby (2)](https://user-images.githubusercontent.com/17780287/155999633-0a1fca6f-d105-4cf1-a5e2-3e73a2c2ed2f.png)

(normalement comme ça tous les boutons redirigent vers la page classement ?)

**Comment by CharlieSaso** [comment]
Ok good pour moi
