### ISSUE TITLE
Recette page stat

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#76]
1. Header filtre jeux passés / en cours 
- [x] Renommer le h6 `Dernière animation / Jeux passés`
- [x] Et le boutons : Jeux en cour : `Dernière animation` // Jeux passé : `Jeux passés`

2. Header tableau Ditributeur
-[ ] Renommer dans tous les th des colonnes : `Nb d'agences participantes au jeu` en `Nb part*` et `% d'agences participantes au jeu` en `% part*`
-[ ] Ajouter une légende au-dessus de rechercher (ferré à droite) :

> *Nb part : Nombre d'agences avec au moins un participant au jeu
> *% part : % d'agences avec au moins un participant au jeu

3. Ajouter une règle de couleur des td % **sur toutes les colonnes** `% part`
- Si chiffre %  inférieur ou égale à 25% => mettre le texte en rouge (rouge mitsu : `#ed1e25`)
- Si chiffre % supérieur ou égal à 75% => mettre le texte en vert (`#1eed60`)

4. Renommer le bouton excel en `Télécharger au format .xls` et le remonter en haut à gauche
-[ ] pour mettre en haut a priori :  https://datatables.net/reference/option/dom
```js
dom: 'Blfrtip',
```
-[ ] changer le texte : 
```js
var buttons = [{
      extend: 'excel',
      text: 'Télécharger au format .xls'
}];`
```
5. Filtrer les jeux affichés dans les tableaux en reprenant bien le profil utilisateur liés

![Page-tableau-–-Test-–-Chaleur-Rugby (2)](https://user-images.githubusercontent.com/17780287/156343454-b95d4b4a-f983-443a-b688-fc999d6183c3.png)

**Comment by CharlieSaso** [comment]
Ok c'est good

**Comment by Sinoe** [comment]
Ok merci dernier round stp :
- Renommer le profil en `Home partenaires`
![Page-tableau-–-Test-–-Chaleur-Rugby (3)](https://user-images.githubusercontent.com/17780287/156377900-ec50a073-e12d-4bfa-a52d-5cdc4a394271.png)

- Je n'ai pas de données pour les Business partners :
![Page-tableau-–-Test-–-Chaleur-Rugby (4)](https://user-images.githubusercontent.com/17780287/156378030-aa242b77-aa13-43e4-9692-eb634f8f51c7.png)

- Dans les colonnes Ditributeurs, enlever `au jeu` (laisser juste `Nb part* - {nom jeu}` et `% part* - {nom jeu}`)
![Page-tableau-–-Test-–-Chaleur-Rugby (5)](https://user-images.githubusercontent.com/17780287/156378118-f8de8e9d-2219-4247-b705-33368c3152a3.png)

Et si pas trop long à faire :
- ajouter le principe des couleurs de % sur tous les tableaux, sinon c'est pas grave,
- Mettre la légende que sur les tableaux Distrib > Distrib
> *Nb part : Nombre d'agences avec au moins un participant au jeu
> *% part : % d'agences avec au moins un participant au jeu

**Comment by CharlieSaso** [comment]
c'est tout bon normalement
