### ISSUE TITLE
Problèmes page statistique - données affichées 

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#79]
En tant que distributeur avec le droit de voir la page stats, les données ne sont pas filtrée sur la page stats :
![Screenshot 2022-03-08 at 13-28-51 Page Statistiques – Chaleur-Rugby](https://user-images.githubusercontent.com/17780287/157238352-2c31bfbe-a747-4780-a08f-f287d68f4ebd.png)

Utilisateur test :
- log : sinoe.grattepanche@gmail.com
- mdp : test123

**Comment by Sinoe** [comment]
Du coup je commente le lien stat dans le header pour les utilisateurs tant que c'est pas reglé (#78 )

**Comment by CharlieSaso** [comment]
Ok corrigé
