### ISSUE TITLE
Page stats > ajout colonne région

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#82]
Peux-tu stp ajouter la colonne `région` sur le tableau Distributeurs > Agences

![Page-Statistiques-–-Chaleur-Rugby](https://user-images.githubusercontent.com/17780287/158853803-b9e967d5-6de8-4e8b-be57-7ed8934ff770.png)

**Comment by CharlieSaso** [comment]
Ok c'est good !

![Page Statistiques – Chaleur-Rugby - Google Chrome](https://user-images.githubusercontent.com/21694987/158999785-6b27fcb8-f731-498c-a592-1f206fde296b.jpg)
