### ISSUE TITLE
Home non connecté - bug match home

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#83]
Y'à un truc chelou quand on est pas connecté sur la home (ça fait pas ça quand on est connecté) :
![Chaleur-Rugby (4)](https://user-images.githubusercontent.com/17780287/158977443-2e4d5dd2-12de-4c27-b10d-d69743a9a382.png)

C'est parce qu'il y a pas de match sélectionné dans l'admin ?

**Comment by CharlieSaso** [comment]
Ok corrigé
