### ISSUE TITLE
Page statistiques - HP > Sociétés > ajout de la colonne région

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#85]
Peux-tu stp ajouter la colonne région sur la page stats HP > Sociétés :
![Page-Statistiques-–-Chaleur-Rugby (1)](https://user-images.githubusercontent.com/17780287/159455969-21bc6c90-8041-4cf4-be0a-d8cf8d1da92f.png)

**Comment by CharlieSaso** [comment]
Ok ajouté
