### ISSUE TITLE
Page statistiques > changement de wording à récupérer en local

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#86]
Peux-tu récupérer la page stats de la prod stp :
MAJ wording `dernière animation` 
![Page-Statistiques-–-Chaleur-Rugby (2)](https://user-images.githubusercontent.com/17780287/159457265-f8fdf83c-e090-4d81-a240-42d595dfefc6.png)

**Comment by CharlieSaso** [comment]
Ok récupéré
