### ISSUE TITLE
Suppression partie CTA / jeu prono de la home - code à récupérer

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#87]
Pour infos, j'ai enlever la partie Prono de la home Distributeur directement en prod :

Ligne 137 :
```html
<!-- PRONOSTICS  - FIN ANIMATION 01/04 - commentaire sur cette partie - code ajouter dans template-parts/home-prono.php-->
```
Le code a été ajouté sur le fichier :
`/home/mitsubishi/chaleur-rugby/wp-content/themes/chaleur-rugby/template-parts/home-prono.php`

Si tu peux récupérer les fichiers en local stp

**Comment by CharlieSaso** [comment]
Ok pour moi
