### ISSUE TITLE
ZAPIER // Mise en place pour les quizz HP 4 - 5 - 6

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#90]
Le client a publié les quizz 4 - 5 - 6 pour lesquels il faudrait mettre en place les zapier stp (le quizz 4 commence lundi prochain).

**QUIZZ 4 ( Rugby - Culture générale  ) :**
Page jeu : https://www.chaleur-rugby.com/wp-admin/post.php?post=5143&action=edit
Admin Drimify : https://go.drimify.com/update/?uid=1329207677624ffc068004e086651423-624ffc0680053
ID Drimify : `1329207677624ffc068004e086651423-624ffc0680053`
Référence Drimify : `Quizz HP - Rugby - Culture générale - 11 Avril au 18 Avril`

**QUIZZ 5 (Mister Slim):**
Page jeu : https://www.chaleur-rugby.com/wp-admin/post.php?post=5145&action=edit
Admin Drimify : https://go.drimify.com/update/?uid=1552938052624fffda087d8397180794-624fffda087dc
ID Drimify : `1552938052624fffda087d8397180794-624fffda087dc`
Référence Drimify : `Quizz HP - Mister Slim - 18 Avril au 25 Avril`

**QUIZZ 6 (Rugby - Compétition) :**
Page jeu : https://www.chaleur-rugby.com/wp-admin/post.php?post=5143&action=edit
Admin Drimify : https://go.drimify.com/update/?uid=642941910625001ef2952b803769927-625001ef29530
ID Drimify : `642941910625001ef2952b803769927-625001ef29530`
Référence Drimify : `Quizz HP - Rugby - Compétition - 25 Avril au 30 Avril`

J'ai vérifier les config sur le WP, c'est OK pour moi

**Comment by CharlieSaso** [comment]
Ok c'est good pour moi
![My Zaps  Zapier - Google Chrome_3](https://user-images.githubusercontent.com/21694987/162424032-e4f4ff97-3341-4f73-9fb0-5031de91b1c1.jpg)
