### ISSUE TITLE
Retours Concours Photos Vidéo - avec retours clients

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#93]
**1. HOME**
- [x] Responsive : remonter la bulle au-dessus des services sur mobile
![Chaleur-Rugby (7)](https://user-images.githubusercontent.com/17780287/163429097-63168442-4340-4180-9aed-94f0eef9b9c0.png)

--------------------------------------------------------------------------------------------------

**4. ADMIN PHOTO LISTE**
- [x] Revoir les titres d'état des filtres `En attente` `Validées` `Refusées`
![Page-admin-concours-photos-–-Chaleur-Rugby (6)](https://user-images.githubusercontent.com/17780287/163164942-7eb969fd-1049-4f3a-8b0a-bd53b3887e0f.png)
- [x] Ordonner le tableau par date de participation desc
- [x] Forcer le passage à la ligne si nécessaire dans le tableau
![Page-admin-concours-photos-–-Chaleur-Rugby](https://user-images.githubusercontent.com/17780287/163153057-e8f95354-0ea4-46ab-8eb4-871a5b04a07b.png)
- [x] Ne pas afficher la colonne Photo event
![Page-admin-concours-photos-–-Chaleur-Rugby (5)](https://user-images.githubusercontent.com/17780287/163164026-4c058042-5b44-4683-95e4-8e685df8f720.png)
- [x] Styler les boutons de validation 
![Page-admin-concours-photos-–-Chaleur-Rugby (1)](https://user-images.githubusercontent.com/17780287/163153348-b6980e0d-313b-4ce5-87de-d65eaa8d5218.png)
- [x] Bug : à la validation / refus d'une participation les lignes n'ont pas le même nombre de colonne
![Page-admin-concours-photos-–-Chaleur-Rugby (3)](https://user-images.githubusercontent.com/17780287/163153844-a95e27da-0554-40ae-a414-c28f415b0027.png)

--------------------------------------------------------------------------------------------------

**4bis. ADMIN PHOTO POPIN**
- [x] Styler le tableau détail des participation
![Page-admin-concours-photos-–-Chaleur-Rugby (2)](https://user-images.githubusercontent.com/17780287/163153481-f080ac04-ec53-4ffc-bdd7-10c39180f34c.png)
- [x] Ne pas rendre administrable les points gagnés (uniquement le nombre de participation et en déduire en JS le nombre de points),
- [x] ajouter les boutons valider / refuser sur la popin détail
![Page-admin-concours-photos-–-Chaleur-Rugby (4)](https://user-images.githubusercontent.com/17780287/163163632-1284be58-e65f-4161-947a-748b0a874364.png)

--------------------------------------------------------------------------------------------------

**5. ADMIN VIDEO LISTE**
- [x] Revoir les titres d'état des filtres `En attente` `Validées` `Refusées`
![Page-admin-concours-photos-–-Chaleur-Rugby (6)](https://user-images.githubusercontent.com/17780287/163164942-7eb969fd-1049-4f3a-8b0a-bd53b3887e0f.png)
- [x] Ordonner le tableau par date de participation desc
- [x] Ajouter les boutons d'actions (éditer)
- [x] Ajouter un lien pour DL la vidéo (`<a href="path_to_file" download="">Télécharger la vidéo</a>`)

--------------------------------------------------------------------------------------------------

**5bis. ADMIN VIDEO POPIN**
- [x] ajouter les boutons valider / refuser sur la popin détail
- [x] ajouter le champs iframe administrable depuis la page tableau admin
![Page-admin-concours-videos-–-Chaleur-Rugby](https://user-images.githubusercontent.com/17780287/163430957-c2b761d8-21a8-40d0-b47a-2f90009e9421.png)

--------------------------------------------------------------------------------------------------

**6. MAILS**
- [x] Envoyer les mails des hooks en html 
![Votre-participation-au-concours-Chaleur-Rugby-Le-XV-de-Mitsubishi-Electric-à-été-validée-sinoe-grattepanche-gmail-com-Gmail](https://user-images.githubusercontent.com/17780287/163148078-8a27ca36-d914-4a67-a4e0-860daa0fb9dd.png)

--------------------------------------------------------------------------------------------------

**7. DIVERS**
- [x] Suite à une participation au concours photo, envoyer un mail à l'user sélectionné (ajouter un champs caché dans le formulaire et le mettre à jour en fonction de la sélection du participant, dans l'admin contact on rajoutera le mail ?) 
On va ajouter l'information du mail interlocuteur Mitsu à la liste CPT `Interlocuteur MEE` - j'attends la liste de la part du client
![Contact-Form-7-‹-Chaleur-Rugby-—-WordPress](https://user-images.githubusercontent.com/17780287/163166197-d3575f12-657a-45d8-bbd7-f399287fa07e.png)
**Liste des interlocuteurs :**

Nom interlocuter | mail
-- | --
Laurent INTERNICOLA | laurent.internicola@fra.mee.com
Laurent VERRIER | laurent.verrier@fra.mee.com
Rémi BARDY | remi.bardy@fra.mee.com
Thomas LEBAILLIF | thomas.lebaillif@fra.mee.com
Thierry MARIDAT | thierry.maridat@fra.mee.com
Frédéric ROQUES | frederic.roques@fra.mee.com
Franck BRIGHI | franck.brighi@fra.mee.com
Valérie CESAREO | valerie.cesareo@fra.mee.com
Alexandre BOGATKO | alexandre.bogatko@fra.mee.com
Cyril BRAENDLE | cyril.braendle@fra.mee.com
Julien BRETHOMÉ | julien.brethome@fra.mee.com
Stephen CADOUX | stephen.cadoux@fra.mee.com
Guillaume LHUILLIER | guillaume.lhuillier@fra.mee.com
Gauthier PAQUIS | gauthier.paquis@fra.mee.com
Anne LARTIGUE | anne.lartigue@fra.mee.com
Vincent GUERIN | vincent.guerin@fra.mee.com

- [x] Pour les utilisateurs ME : ajouter un lien dans le header vers la page d'administration des photos (en rouge)
![Galerie-Videos-–-Chaleur-Rugby (1)](https://user-images.githubusercontent.com/17780287/163166828-c4210658-8ac3-42cd-b363-10cca1e967b9.png)

**Comment by Sinoe** [comment]
Pour infos, j'ai regarder pour mettre Slick dans la fancybox :
J'ai réussi à faire ça qui n'est pas si mal je trouve : https://chaleur-rugby.fk-agency.net/galerie-photo/?pagination=1

Je te laisse regarder et voir si ça peut passer.
`footer.php`
```html
<!-- Chargement des scripts + css slick -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css" integrity="sha512-wR4oNhLBHf7smjy0K4oqzdWumd+r5/+6QO/vDda76MW5iug4PT7v86FoEkySIJft3XA0Ae6axhIvHrqwm793Nw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script>
	$(document).ready(function(){
		// Fancybox : prevent grab effect pour que celui de slick soit prioritaire + reload slick height on display
		Fancybox.bind(".c-gallery__item--image", {
			touch : false,
			infinite : false,
			dragToClose: false,
			on: {
				reveal:(fancybox, slide) => {
					console.log(`reveal!`);
					$('.container_slider_slick').slick('setPosition');
				},
			}
		});
		// Slick : normal
		$('.container_slider_slick').slick({
			slidesToShow: 1,
			slidesToScroll: 1,
			arrows: false,
			dots: true,
			infinite: false, 
			variableWidth: false,
			adaptiveHeight: true
		});
	});
</script>
<style>
	/* Problème de calcul de width qui vient de la fancybox je pense, il faut définir pas mal de largeur pour que ça fonctionne */
	.c-gallery__item--images--slider-test{
		max-width: 850px;
		width:92vw;
		overflow: hidden;
		display:block;
	}
	.c-gallery__item--images--slider-test .container_slider_slick{
		max-width:850px;
		width:90vw;
		margin:0 auto;
		display:block;
	}
	.c-gallery__item--images--slider-test .slide{
		width:auto;
		max-width:850px;
		display:block;
	}
	.c-gallery__item--images--slider-test .slide img{
		width:auto;
		max-width:100%;
		display:block;
		margin:0 auto;
	}
</style>
```
`page-gallerie-concours-photo.php` (ajout des container slick + slide pour gérer le display:block et les largeurs)
```html
<div class="o-wrapper">
	TEST SLICK
	<div class="c-gallery__container">
<?php

	if ( $the_query->have_posts() ) :
		while ( $the_query->have_posts() ) :
			$the_query->the_post();
			$the_id = get_the_ID();
			$featureImage = get_the_post_thumbnail_url($the_id, 'large');
			$id_user = get_field('id_user');
			$descriptif = get_field('descriptif');
			$metaSociete = get_user_meta($id_user, 'societe_distributeur');
			$points_de_recompense = get_field('points_de_recompense');
			$thisPost = get_post($the_id);
			$additionalImage = apply_filters('the_content',$thisPost->post_content);
			$additionalImage = strip_tags($additionalImage);
			$additionalImage = explode(",", $additionalImage);
			$countimage = 1;

?>

		<div class="c-gallery__item">

			<div class="c-gallery__item--image" style="background-image: url(<?php echo $featureImage ?>);" data-fancybox data-src="#c-gallery__item--images-<?php echo $the_id ?>-test">

				<div class="c-gallery__item--reward"> <?php echo $points_de_recompense ?>  pts</div>
			</div>
			<div class="c-gallery__item--societe">
				<?php echo $metaSociete[0] ?>
			</div>

			<div id="c-gallery__item--images-<?php echo $the_id ?>-test" class="c-gallery__item--images-test" style="display: none;" >
				<div class="c-gallery__item--images--slider-test">
					<div class="container_slider_slick">
						<div class="slide"><img src="<?php echo $featureImage ?>" alt="" class="visible" data-target="slide-<?php echo $countimage ?>-<?php echo $the_id ?>"/></div>
						<?php foreach ($additionalImage as $key => $value):?>
							<?php if (strlen($value) > 1 ) : ?>
								<div class="slide"><img src="<?php echo $value ?>"   alt="" data-target="slide-<?php echo $countimage ?>-<?php echo $the_id ?>"/></div>
							<?php endif; ?>
						<?php endforeach ?>
					</div>

				</div>

				<div class="c-gallery__item--images--more">
					<h4><?php echo $metaSociete[0] ?></h4>
					<p><?php echo $descriptif ?></p>
				</div>
			</div>

		</div>
```

**Comment by CharlieSaso** [comment]
tu m'as mis tellement bien !! cimer !

**Comment by Sinoe** [comment]
Fichier à récupérer :
`footer.php` => styles slider + fancybox
`page-gallerie-concours-video.php` => ajout nom de la société sur la thumb
